"""Programmatic structure presets for examples and tests.

All presets use the crystallographic primitive cell (unique periodic sites)
so that ``structure.formula`` matches the expected chemical formula.  Cell
boundary atoms are generated by the scene builder / supercell machinery, not
by duplicating sites in the canonical structure.
"""

from __future__ import annotations

import numpy as np

from crystalfig.model.lattice import Lattice
from crystalfig.model.site import Site
from crystalfig.model.structure import CrystalStructure


def rocksalt_structure(a: float = 5.64, *, conventional: bool = False) -> CrystalStructure:
    """NaCl rocksalt structure.

    By default returns the primitive FCC cell (2 atoms). Pass
    ``conventional=True`` for the intuitive cubic cell (8 atoms) used in
    publication figures.
    """
    if conventional:
        lattice = Lattice.from_parameters(a, a, a, 90.0, 90.0, 90.0)
        sites = [
            Site(frac_coords=[0.0, 0.0, 0.0], species="Na"),
            Site(frac_coords=[0.5, 0.5, 0.0], species="Cl"),
            Site(frac_coords=[0.5, 0.0, 0.5], species="Cl"),
            Site(frac_coords=[0.0, 0.5, 0.5], species="Cl"),
            Site(frac_coords=[0.5, 0.5, 0.5], species="Na"),
            Site(frac_coords=[0.5, 0.0, 0.0], species="Na"),
            Site(frac_coords=[0.0, 0.5, 0.0], species="Na"),
            Site(frac_coords=[0.0, 0.0, 0.5], species="Na"),
        ]
        return CrystalStructure(lattice=lattice, sites=sites)
    # FCC primitive vectors
    lattice = Lattice(np.array([
        [0.0, a / 2, a / 2],
        [a / 2, 0.0, a / 2],
        [a / 2, a / 2, 0.0],
    ]))
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Na"),
        Site(frac_coords=[0.5, 0.5, 0.5], species="Cl"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def diamond_structure(a: float = 5.43, *, conventional: bool = False) -> CrystalStructure:
    """Diamond cubic Si structure.

    By default returns the primitive FCC cell (2 atoms). Pass
    ``conventional=True`` for the conventional cubic cell (8 atoms).
    """
    if conventional:
        lattice = Lattice.from_parameters(a, a, a, 90.0, 90.0, 90.0)
        sites = [
            Site(frac_coords=[0.0, 0.0, 0.0], species="Si"),
            Site(frac_coords=[0.0, 0.5, 0.5], species="Si"),
            Site(frac_coords=[0.5, 0.0, 0.5], species="Si"),
            Site(frac_coords=[0.5, 0.5, 0.0], species="Si"),
            Site(frac_coords=[0.25, 0.25, 0.25], species="Si"),
            Site(frac_coords=[0.25, 0.75, 0.75], species="Si"),
            Site(frac_coords=[0.75, 0.25, 0.75], species="Si"),
            Site(frac_coords=[0.75, 0.75, 0.25], species="Si"),
        ]
        return CrystalStructure(lattice=lattice, sites=sites)
    lattice = Lattice(np.array([
        [0.0, a / 2, a / 2],
        [a / 2, 0.0, a / 2],
        [a / 2, a / 2, 0.0],
    ]))
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Si"),
        Site(frac_coords=[0.25, 0.25, 0.25], species="Si"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def perovskite_structure(a: float = 3.95, c: float | None = None) -> CrystalStructure:
    """BaTiO3 tetragonal perovskite (primitive cell, 5 atoms)."""
    c = c or a
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 90.0)
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Ba"),
        Site(frac_coords=[0.5, 0.5, 0.5], species="Ti"),
        Site(frac_coords=[0.5, 0.5, 0.0], species="O"),
        Site(frac_coords=[0.5, 0.0, 0.5], species="O"),
        Site(frac_coords=[0.0, 0.5, 0.5], species="O"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def rutile_structure(a: float = 4.59, c: float = 2.96) -> CrystalStructure:
    """TiO2 rutile structure (primitive tetragonal cell, 6 atoms)."""
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 90.0)
    u = 0.305
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Ti"),
        Site(frac_coords=[0.5, 0.5, 0.5], species="Ti"),
        Site(frac_coords=[u, u, 0.0], species="O"),
        Site(frac_coords=[1 - u, 1 - u, 0.0], species="O"),
        Site(frac_coords=[0.5 + u, 0.5 - u, 0.5], species="O"),
        Site(frac_coords=[0.5 - u, 0.5 + u, 0.5], species="O"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def wurtzite_structure(a: float = 3.25, c: float = 5.21) -> CrystalStructure:
    """ZnO wurtzite structure (primitive hexagonal cell, 4 atoms).

    Lattice parameters follow the common experimental/computational values
    (a ~ 3.25 Å, c ~ 5.21 Å; internal parameter u ~ 0.382).
    """
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 120.0)
    u = 0.382
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Zn"),
        Site(frac_coords=[1 / 3, 2 / 3, 0.5], species="Zn"),
        Site(frac_coords=[0.0, 0.0, u], species="O"),
        Site(frac_coords=[1 / 3, 2 / 3, 0.5 + u], species="O"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def mos2_structure(a: float = 3.19, c: float = 12.3) -> CrystalStructure:
    """2H-MoS2 layered structure (primitive hexagonal cell, 6 atoms).

    Space group P6_3/mmc (No. 194): Mo at 2d (1/3, 2/3, 1/4), S at 4f
    (1/3, 2/3, z) with z ~ 0.621.
    """
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 120.0)
    z = 0.621
    sites = [
        Site(frac_coords=[1 / 3, 2 / 3, 1 / 4], species="Mo"),
        Site(frac_coords=[2 / 3, 1 / 3, 3 / 4], species="Mo"),
        Site(frac_coords=[1 / 3, 2 / 3, z], species="S"),
        Site(frac_coords=[2 / 3, 1 / 3, z + 1 / 2], species="S"),
        Site(frac_coords=[2 / 3, 1 / 3, 1 - z], species="S"),
        Site(frac_coords=[1 / 3, 2 / 3, 1 / 2 - z], species="S"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)
