"""Programmatic structure presets for examples and tests.

All presets use the crystallographic primitive cell (unique periodic sites)
so that ``structure.formula`` matches the expected chemical formula.  Cell
boundary atoms are generated by the scene builder / supercell machinery, not
by duplicating sites in the canonical structure.
"""

from __future__ import annotations

import numpy as np

from crystalfig.model.lattice import Lattice
from crystalfig.model.site import Site
from crystalfig.model.structure import CrystalStructure


def rocksalt_structure(a: float = 5.64) -> CrystalStructure:
    """NaCl rocksalt structure (primitive cell, 2 atoms)."""
    # FCC primitive vectors
    lattice = Lattice(np.array([
        [0.0, a / 2, a / 2],
        [a / 2, 0.0, a / 2],
        [a / 2, a / 2, 0.0],
    ]))
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Na"),
        Site(frac_coords=[0.5, 0.5, 0.5], species="Cl"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def diamond_structure(a: float = 5.43) -> CrystalStructure:
    """Diamond cubic Si structure (primitive cell, 2 atoms)."""
    lattice = Lattice(np.array([
        [0.0, a / 2, a / 2],
        [a / 2, 0.0, a / 2],
        [a / 2, a / 2, 0.0],
    ]))
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Si"),
        Site(frac_coords=[0.25, 0.25, 0.25], species="Si"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def perovskite_structure(a: float = 3.95, c: float | None = None) -> CrystalStructure:
    """BaTiO3 tetragonal perovskite (primitive cell, 5 atoms)."""
    c = c or a
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 90.0)
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Ba"),
        Site(frac_coords=[0.5, 0.5, 0.5], species="Ti"),
        Site(frac_coords=[0.5, 0.5, 0.0], species="O"),
        Site(frac_coords=[0.5, 0.0, 0.5], species="O"),
        Site(frac_coords=[0.0, 0.5, 0.5], species="O"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def rutile_structure(a: float = 4.59, c: float = 2.96) -> CrystalStructure:
    """TiO2 rutile structure (primitive tetragonal cell, 6 atoms)."""
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 90.0)
    u = 0.305
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Ti"),
        Site(frac_coords=[0.5, 0.5, 0.5], species="Ti"),
        Site(frac_coords=[u, u, 0.0], species="O"),
        Site(frac_coords=[1 - u, 1 - u, 0.0], species="O"),
        Site(frac_coords=[0.5 + u, 0.5 - u, 0.5], species="O"),
        Site(frac_coords=[0.5 - u, 0.5 + u, 0.5], species="O"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def wurtzite_structure(a: float = 3.82, c: float = 6.26) -> CrystalStructure:
    """ZnO wurtzite structure (primitive hexagonal cell, 4 atoms)."""
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 120.0)
    sites = [
        Site(frac_coords=[0.0, 0.0, 0.0], species="Zn"),
        Site(frac_coords=[1 / 3, 2 / 3, 0.5], species="Zn"),
        Site(frac_coords=[0.0, 0.0, 0.375], species="O"),
        Site(frac_coords=[1 / 3, 2 / 3, 0.875], species="O"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)


def mos2_structure(a: float = 3.19, c: float = 12.3) -> CrystalStructure:
    """MoS2 layered structure (primitive hexagonal cell, 6 atoms)."""
    lattice = Lattice.from_parameters(a, a, c, 90.0, 90.0, 120.0)
    sites = [
        Site(frac_coords=[1 / 3, 2 / 3, 0.25], species="Mo"),
        Site(frac_coords=[2 / 3, 1 / 3, 0.75], species="Mo"),
        Site(frac_coords=[1 / 3, 2 / 3, 0.37], species="S"),
        Site(frac_coords=[2 / 3, 1 / 3, 0.63], species="S"),
        Site(frac_coords=[1 / 3, 2 / 3, 0.13], species="S"),
        Site(frac_coords=[2 / 3, 1 / 3, 0.87], species="S"),
    ]
    return CrystalStructure(lattice=lattice, sites=sites)
